# Generated by Django 5.1.3 on 2024-11-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEINFRA_MG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REGIAO', models.CharField(max_length=100)),
                ('CODIGO', models.CharField(max_length=50)),
                ('DESCRICAO_DE_SERVICO', models.TextField(verbose_name='DESCRIÇÃO DE SERVIÇO')),
                ('UNIDADE', models.CharField(max_length=20)),
                ('CUSTO_UNITARIO', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='CUSTO UNITÁRIO')),
            ],
            options={
                'db_table': 'SEINFRA_MG',
                'unique_together': {('CODIGO', 'REGIAO')},
            },
        ),
    ]
