# Generated by Django 5.1.3 on 2024-11-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seinfra_mg',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='seinfra_mg',
            name='CODIGO',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seinfra_mg',
            name='CUSTO_UNITARIO',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='seinfra_mg',
            name='DESCRICAO_DE_SERVICO',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seinfra_mg',
            name='REGIAO',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seinfra_mg',
            name='UNIDADE',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
